name: Deploy GPT API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t phihungandre/gpt-api .
        docker push phihungandre/gpt-api

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Install Docker on VM
      run: |
        ssh -o StrictHostKeyChecking=no phi_hung_andre@34.68.84.193 "
        sudo apt-get update &&
        sudo apt-get install -y docker.io"

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no phi_hung_andre@34.68.84.193 "docker pull phihungandre/gpt-api && docker run -d -p 5000:5000 phihungandre/gpt-api"