name: Deploy GPT API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t phihungandre/gpt-api .
        docker push phihungandre/gpt-api

    - name: Deploy to VM
      run: |
        ssh phihungandre@10.0.2.15 "docker pull phihungandre/gpt-api && docker run -d -p 5000:5000 phihungandre/gpt-api"